# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Adwaita darker
#include current-theme.conf
# END_KITTY_THEME

font_family JetBrainsMono Nerd Font Propo Light
font_size 17
disable_ligatures never
enable_audio_bell no
cursor_shape block
remember_window_size no 
window_padding_width 25 

# cursor animation #
#cursor_trail 15
#cursor_trail_start_threshold 0
#cursor_trail_decay 0 0.5


cursor_stop_blinking_after 0
cursor_blink_interval 0
background_opacity 1
confirm_os_window_close 0
selection_background #5b9bf8
selection_foreground #000000

background #242424
#background #181825
foreground #fafafa

#black
color0 #030303
#red
color1 #e53935
#green
color2 #4caf50
#yellow
color3 #fbc02d
#blue
color4 #3c84f7
#purple
color5 #ab47bc
#teal
color6 #009688 
#lightgrey
color7 #cccccc


#darkgrey
color8 #242424
#lightred
color9 #f44336
#lightgreen
color10 #66bb6a
#lightyellow
color11 #ffd600
#lightblue
color12 #5b9bf8
#lightpurple
color13 #ba68c8
#lightteal
color14 #4db6ac 
#white
color15 #fafafa
